### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by HappyDay-design** [D3TRU04/Selfless_Traffic_Routing_Testbed#1]
Thank you for sharing your models!
```
 Traceback (most recent call last):
  File "/home/osboxes/Desktop/Selfless_Traffic_Routing_Testbed/main.py", line 6, in <module>
    from core.STR_SUMO import StrSumo
  File "/home/osboxes/Desktop/Selfless_Traffic_Routing_Testbed/core/STR_SUMO.py", line 7, in <module>
    from core.target_vehicles_generation_protocols import *
ModuleNotFoundError: No module named 'core.target_vehicles_generation_protocols'
```
The core folder is missing `STR_SUMO_overall_performance`, `target_vehicles_generation_protocols`

**Comment by HappyDay-design** [comment]
But I copied all of them from [[](https://github.com/Local-Coding-Buddy/DUE-STR.git)](https://github.com/Local-Coding-Buddy/DUE-STR.git)
